#!/bin/bash

set -eu
prog_name=$(basename $0)

DBUSER=
DBNAME=openspending
GIT_REPO=http://github.com/openspending/openspending.git
JS_REPO=http://github.com/openspending/openspendingjs.git
TARGET_DIR=openspending
VIRTUALENV=virtualenv
CREATEDBOPTS="-E utf-8"
SOLR_DIR=solr

while [ $# -gt 0 ];
do
	case "$1" in
		--git-repo) 
		  GIT_REPO=$2
		  shift 2
		  ;;
		--js-repo)
		  JS_REPO=$2
		  shift 2
		  ;;
		--target-dir)
		  TARGET_DIR=$2
		  shift 2
		  ;;
		--db-user)
		  DBUSER=$2
		  shift 2
		  ;;
		--db-name)
		  DBNAME=$2
		  shift 2
		  ;;
    --virtualenv)
      VIRTUALENV=$2
      shift 2
      ;;
    --solr-dir)
      SOLD_DIR=$2
      shift 2
      ;;
		*)
		  echo ${prog_name}: unrecognised option: $1
		  exit 1
		  ;;
    esac
done


if [ -d $TARGET_DIR ]; then
	echo ${prog_name}: Directory openspending already exists
	exit 1
fi


git clone $GIT_REPO $TARGET_DIR
cd $TARGET_DIR

git clone $JS_REPO
ln -s openspendingjs openspending/ui/public/static/openspendingjs


setup_virtualenv () {
# should explicitly use python2.7
	$VIRTUALENV ./pyenv

	set +u
	source ./pyenv/bin/activate
	set -u
}

install_requirements () {
	pip install nose==1.1.2
	pip install PasteScript==1.7.5
	pip install -r requirements.txt -e .
	pip install psycopg2
}

setup_virtualenv
install_requirements


if [ $DBUSER ]; then
  CREATEDBOPTS="$CREATEDBOPTS --owner $DBUSER";
fi  
createdb $CREATEDBOPTS $DBNAME;

cp development.ini_tmpl development.ini

cat development.ini_tmpl | \
	sed "s/^openspending.db.url = .*$/openspending.db.url = postgresql:\/\/${DBUSER}@localhost\/${DBNAME}/" > \
	development.ini

ostool development.ini db init

git submodule init && git submodule update
(cd doc && make clean html)

# SOLR

PWD=`pwd`
CONFIG="$PWD/$TARGET_DIR/solr/openspending_schema.xml"
mv $SOLR_DIR/example/solr/collection1/conf/schema.xml $SOLR_DIR/example/solr/collection1/conf/schema.xml.back
ln -s $CONFIG $SOLR_DIR/example/solr/collection1/conf/schema.xml
