#!/bin/bash

cat > ~/hba.patch <<EOF
--- a/pg_hba.conf       2013-03-03 03:00:59.613485177 +0000
+++ b/pg_hba.conf       2013-03-03 03:01:20.728747046 +0000
@@ -87,7 +87,7 @@
 # TYPE  DATABASE        USER            ADDRESS                 METHOD
 
 # "local" is for Unix domain socket connections only
-local   all             all                                     peer
+local   all             all                                     md5
 # IPv4 local connections:
 host    all             all             127.0.0.1/32            md5
 # IPv6 local connections:
EOF

fix_pghba () { 
		  ( cd /etc/postgresql/9.1/main/ ; patch -p1 < ~/hba.patch )
}
